repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-json                # checks if json files are valid
    - id: check-added-large-files   # checks if large files were added
    - id: check-merge-conflict      # checks if all merge conflicts were resolved
    - id: check-yaml                # checks if yaml files are valid
    - id: debug-statements          # checks if debug statements are to be commited
    - id: end-of-file-fixer         # fixes missing line ending in end of file
    - id: mixed-line-ending         # fixes line files line ending
      args: [--fix=lf]
    - id: trailing-whitespace       # removes trailing whitespaces from text files
